language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d7e8105501d7_key -iv $encrypted_d7e8105501d7_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
